---
abstract: 'Resolve public identifiers and remap system identifiers'
author:
  - 'Jeff Fearn <jfearn@cpan.org>'
build_requires:
  LWP::Simple: 0
  Test::More: 0
  Text::ParseWords: 0
  URI::URL: 0
  XML::Parser: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Catalog
provides:
  XML::Catalog:
    file: lib/XML/Catalog.pm
    version: v1.0.0_1
  XML::Catalog::XML:
    file: lib/XML/Catalog.pm
    version: 0
requires:
  LWP::Simple: 0
  Text::ParseWords: 0
  URI::URL: 0
  XML::Parser: 0
resources:
  license: http://dev.perl.org/licenses/
version: v1.0.0_1
